services:
  web:
    build:
      context: .
    image: lms-backend:latest
    depends_on:
      - db
    volumes:
      - ./:/code:ro
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}

    ports:
      - "8000:8000"
    command: >
      bash app/scripts/prestart.sh

