services:
  web:
    build: .
    image: lms-backend:latest
    depends_on:
      - db
    volumes:
      - ./:/code:ro
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    ports:
      - "8001:8000"  # No conflict with main branch

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8082:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  nginx-test:
    image: nginx:latest
    depends_on:
      - web
    volumes:
      - ./nginx-test/test.conf:/etc/nginx/conf.d/test.conf  # Use test.conf for the test branch
    ports:
      - "8083:80"  # Use a different port to avoid conflict with the main branch Nginx
    restart: always

volumes:
  postgres_data:
  pgadmin_data:
