"""remove the teacher access table and add cascade delete to all the existing table that needs it.

Revision ID: 1e82bf0ba8f3
Revises: 7fda5d9248b2
Create Date: 2024-11-25 13:49:26.996665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e82bf0ba8f3'
down_revision: Union[str, None] = '7fda5d9248b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_template_course_access_template_course_access_id', table_name='template_course_access')
    op.drop_table('template_course_access')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_course_access',
    sa.Column('template_course_access_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('template_course_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], name='template_course_access_teacher_id_fkey'),
    sa.ForeignKeyConstraint(['template_course_id'], ['template_course.template_course_id'], name='template_course_access_template_course_id_fkey'),
    sa.PrimaryKeyConstraint('template_course_access_id', name='template_course_access_pkey')
    )
    op.create_index('ix_template_course_access_template_course_access_id', 'template_course_access', ['template_course_access_id'], unique=True)
    # ### end Alembic commands ###
