"""usersetting updated

Revision ID: 2dd4d961e9da
Revises: 4fe3f7d710d9
Create Date: 2024-10-10 17:45:30.695863

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2dd4d961e9da"
down_revision: Union[str, None] = "4fe3f7d710d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_settings",
        "notification_preference",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        existing_nullable=False,
        postgresql_using="notification_preference::json",
    )

    op.alter_column(
        "user_settings",
        "privacy_preference",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        existing_nullable=False,
        postgresql_using="privacy_preference::json",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_settings",
        "privacy_preference",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_settings",
        "notification_preference",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
