"""add title and description field to the section_specefic_content table

Revision ID: 36a78aca72b6
Revises: 3dac1775b0cf
Create Date: 2024-11-08 14:41:29.755481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a78aca72b6'
down_revision: Union[str, None] = '3dac1775b0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section_exclusive_content', sa.Column('title', sa.String(), nullable=True))
    op.add_column('section_exclusive_content', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section_exclusive_content', 'description')
    op.drop_column('section_exclusive_content', 'title')
    # ### end Alembic commands ###
