"""drop the section_exclusive_content table and then recreate it with different fields.

Revision ID: 3dac1775b0cf
Revises: a6326c69d7df
Create Date: 2024-11-01 13:01:52.476845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3dac1775b0cf'
down_revision: Union[str, None] = 'a6326c69d7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section_exclusive_content', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('section_exclusive_content', sa.Column('library_item_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'section_exclusive_content', 'global_library', ['library_item_id'], ['library_id'])
    op.create_foreign_key(None, 'section_exclusive_content', 'user', ['user_id'], ['user_id'])
    op.drop_column('section_exclusive_content', 'content_file')
    op.drop_column('section_exclusive_content', 'created_at')
    op.drop_column('section_exclusive_content', 'content_type')
    op.drop_column('section_exclusive_content', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section_exclusive_content', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('section_exclusive_content', sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('section_exclusive_content', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('section_exclusive_content', sa.Column('content_file', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'section_exclusive_content', type_='foreignkey')
    op.drop_constraint(None, 'section_exclusive_content', type_='foreignkey')
    op.drop_column('section_exclusive_content', 'library_item_id')
    op.drop_column('section_exclusive_content', 'user_id')
    # ### end Alembic commands ###
