"""global library updated

Revision ID: 4f636593f906
Revises: 2dd4d961e9da
Create Date: 2024-10-20 13:37:53.679382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f636593f906'
down_revision: Union[str, None] = '2dd4d961e9da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_library', sa.Column('author', sa.String(), nullable=True))
    op.add_column('global_library', sa.Column('visibility', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_library', 'visibility')
    op.drop_column('global_library', 'author')
    # ### end Alembic commands ###
