"""created tables : User, GlobalLibrary, CourseMaterials, Admin, Teacher, Student, Branch, TemplateCourse, UserSettings, Section, SectionExclusiveContent, Assignment, AssignmentMaterial, StudentStats, Inbox, Discussion, DiscussionMessage, DiscussionReplyMessage, AssignmentQuestion, and AssignmentSubmissio

Revision ID: 4fe3f7d710d9
Revises: a37f59963b00
Create Date: 2024-10-10 00:51:50.333408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fe3f7d710d9'
down_revision: Union[str, None] = 'a37f59963b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_library',
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('material_type', sa.String(), nullable=False),
    sa.Column('material_title', sa.String(), nullable=False),
    sa.Column('material_file', sa.String(), nullable=False),
    sa.Column('material_description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('library_id')
    )
    op.create_index(op.f('ix_global_library_library_id'), 'global_library', ['library_id'], unique=True)
    op.create_table('template_course',
    sa.Column('template_course_id', sa.UUID(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('template_description', sa.String(), nullable=True),
    sa.Column('template_year', sa.String(), nullable=True),
    sa.Column('course_outline', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.admin_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.PrimaryKeyConstraint('template_course_id')
    )
    op.create_index(op.f('ix_template_course_template_course_id'), 'template_course', ['template_course_id'], unique=True)
    op.create_table('course_materials',
    sa.Column('course_material_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('template_course_id', sa.UUID(), nullable=True),
    sa.Column('library_item_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['library_item_id'], ['global_library.library_id'], ),
    sa.ForeignKeyConstraint(['template_course_id'], ['template_course.template_course_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('course_material_id')
    )
    op.create_index(op.f('ix_course_materials_course_material_id'), 'course_materials', ['course_material_id'], unique=True)
    op.create_table('section',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.Column('section_code', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('template_course_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ),
    sa.ForeignKeyConstraint(['template_course_id'], ['template_course.template_course_id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_index(op.f('ix_section_section_id'), 'section', ['section_id'], unique=True)
    op.create_table('assignment',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('assignment_type', sa.String(), nullable=False),
    sa.Column('assignment_title', sa.String(), nullable=False),
    sa.Column('assignment_description', sa.String(), nullable=True),
    sa.Column('assignment_question_type', sa.String(), nullable=False),
    sa.Column('number_of_questions', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.section_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_assignment_assignment_id'), 'assignment', ['assignment_id'], unique=True)
    op.create_table('discussion',
    sa.Column('discussion_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.section_id'], ),
    sa.PrimaryKeyConstraint('discussion_id')
    )
    op.create_index(op.f('ix_discussion_discussion_id'), 'discussion', ['discussion_id'], unique=True)
    op.create_table('inbox',
    sa.Column('inbox_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.section_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('inbox_id')
    )
    op.create_index(op.f('ix_inbox_inbox_id'), 'inbox', ['inbox_id'], unique=True)
    op.create_table('section_exclusive_content',
    sa.Column('section_exclusive_content_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('content_file', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.section_id'], ),
    sa.PrimaryKeyConstraint('section_exclusive_content_id')
    )
    op.create_index(op.f('ix_section_exclusive_content_section_exclusive_content_id'), 'section_exclusive_content', ['section_exclusive_content_id'], unique=True)
    op.create_table('student_stats',
    sa.Column('student_stats_id', sa.UUID(), nullable=False),
    sa.Column('exam_name', sa.String(), nullable=False),
    sa.Column('full_marks', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.section_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('student_stats_id')
    )
    op.create_index(op.f('ix_student_stats_student_stats_id'), 'student_stats', ['student_stats_id'], unique=True)
    op.create_table('assignment_material',
    sa.Column('assignment_material_id', sa.UUID(), nullable=False),
    sa.Column('matrial', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.assignment_id'], ),
    sa.PrimaryKeyConstraint('assignment_material_id')
    )
    op.create_index(op.f('ix_assignment_material_assignment_material_id'), 'assignment_material', ['assignment_material_id'], unique=True)
    op.create_table('assignment_question',
    sa.Column('assignment_question_id', sa.UUID(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('expected_answer', sa.String(), nullable=False),
    sa.Column('options_for_mcq', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('question_description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.assignment_id'], ),
    sa.PrimaryKeyConstraint('assignment_question_id')
    )
    op.create_index(op.f('ix_assignment_question_assignment_question_id'), 'assignment_question', ['assignment_question_id'], unique=True)
    op.create_table('assignment_submission',
    sa.Column('assignment_submission_id', sa.UUID(), nullable=False),
    sa.Column('submitted_file', sa.String(), nullable=True),
    sa.Column('grading', sa.String(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.assignment_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('assignment_submission_id')
    )
    op.create_index(op.f('ix_assignment_submission_assignment_submission_id'), 'assignment_submission', ['assignment_submission_id'], unique=True)
    op.create_table('discussion_message',
    sa.Column('discussion_message_id', sa.UUID(), nullable=False),
    sa.Column('discussion_text', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('discussion_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussion.discussion_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('discussion_message_id')
    )
    op.create_index(op.f('ix_discussion_message_discussion_message_id'), 'discussion_message', ['discussion_message_id'], unique=True)
    op.create_table('discussionreplymessage',
    sa.Column('discussion_reply_message_id', sa.UUID(), nullable=False),
    sa.Column('discussion_reply_text', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('discussion_message_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_message_id'], ['discussion_message.discussion_message_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('discussion_reply_message_id')
    )
    op.create_index(op.f('ix_discussionreplymessage_discussion_reply_message_id'), 'discussionreplymessage', ['discussion_reply_message_id'], unique=True)
    op.add_column('student', sa.Column('metric_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'metric_id')
    op.drop_index(op.f('ix_discussionreplymessage_discussion_reply_message_id'), table_name='discussionreplymessage')
    op.drop_table('discussionreplymessage')
    op.drop_index(op.f('ix_discussion_message_discussion_message_id'), table_name='discussion_message')
    op.drop_table('discussion_message')
    op.drop_index(op.f('ix_assignment_submission_assignment_submission_id'), table_name='assignment_submission')
    op.drop_table('assignment_submission')
    op.drop_index(op.f('ix_assignment_question_assignment_question_id'), table_name='assignment_question')
    op.drop_table('assignment_question')
    op.drop_index(op.f('ix_assignment_material_assignment_material_id'), table_name='assignment_material')
    op.drop_table('assignment_material')
    op.drop_index(op.f('ix_student_stats_student_stats_id'), table_name='student_stats')
    op.drop_table('student_stats')
    op.drop_index(op.f('ix_section_exclusive_content_section_exclusive_content_id'), table_name='section_exclusive_content')
    op.drop_table('section_exclusive_content')
    op.drop_index(op.f('ix_inbox_inbox_id'), table_name='inbox')
    op.drop_table('inbox')
    op.drop_index(op.f('ix_discussion_discussion_id'), table_name='discussion')
    op.drop_table('discussion')
    op.drop_index(op.f('ix_assignment_assignment_id'), table_name='assignment')
    op.drop_table('assignment')
    op.drop_index(op.f('ix_section_section_id'), table_name='section')
    op.drop_table('section')
    op.drop_index(op.f('ix_course_materials_course_material_id'), table_name='course_materials')
    op.drop_table('course_materials')
    op.drop_index(op.f('ix_template_course_template_course_id'), table_name='template_course')
    op.drop_table('template_course')
    op.drop_index(op.f('ix_global_library_library_id'), table_name='global_library')
    op.drop_table('global_library')
    # ### end Alembic commands ###
