"""thread table updated

Revision ID: 6404218d6e04
Revises: b663f7ca85ca
Create Date: 2024-12-07 06:21:10.053887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6404218d6e04'
down_revision: Union[str, None] = 'b663f7ca85ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_thread', sa.Column('doctor_notes', sa.String(), nullable=True))
    op.add_column('scenario_thread', sa.Column('diagnosis', sa.String(), nullable=True))
    op.add_column('scenario_thread', sa.Column('treatment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario_thread', 'treatment')
    op.drop_column('scenario_thread', 'diagnosis')
    op.drop_column('scenario_thread', 'doctor_notes')
    # ### end Alembic commands ###
