"""modified table name

Revision ID: 666ab5e80346
Revises: 7a71fb72be0f
Create Date: 2024-10-09 00:15:03.425556

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "666ab5e80346"
down_revision: Union[str, None] = "7a71fb72be0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("usersettings", "user_settings")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("user_settings", "usersettings")
    # ### end Alembic commands ###
