"""foreignkey added

Revision ID: 71eb583fe11e
Revises: c62ace70954c
Create Date: 2024-10-09 01:10:24.963455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71eb583fe11e'
down_revision: Union[str, None] = 'c62ace70954c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'admin', 'user', ['user_id'], ['user_id'])
    op.add_column('branch', sa.Column('institution_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'branch', 'institution', ['institution_id'], ['institution_id'])
    op.add_column('department', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'department', 'branch', ['branch_id'], ['branch_id'])
    op.add_column('student', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('teacher', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('user', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'user', 'branch', ['branch_id'], ['branch_id'])
    op.add_column('user_settings', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'user_settings', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.drop_column('user_settings', 'user_id')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'branch_id')
    op.drop_column('teacher', 'user_id')
    op.drop_column('student', 'user_id')
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'branch_id')
    op.drop_constraint(None, 'branch', type_='foreignkey')
    op.drop_column('branch', 'institution_id')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_column('admin', 'user_id')
    # ### end Alembic commands ###
