"""add branch relationship to scenarios table.

Revision ID: 7816a594ecd9
Revises: af4591d71430
Create Date: 2024-12-01 17:59:57.076550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7816a594ecd9'
down_revision: Union[str, None] = 'af4591d71430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'scenario', 'branch', ['branch_id'], ['branch_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenario', type_='foreignkey')
    op.drop_column('scenario', 'branch_id')
    # ### end Alembic commands ###
