"""created admin,branch,department,instituion,teacher,user

Revision ID: 7a71fb72be0f
Revises: 4c24b761bc1a
Create Date: 2024-10-09 00:12:00.187327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a71fb72be0f'
down_revision: Union[str, None] = '4c24b761bc1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_index(op.f('ix_admin_admin_id'), 'admin', ['admin_id'], unique=True)
    op.create_table('branch',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=False),
    sa.Column('branch_address', sa.String(), nullable=False),
    sa.Column('branch_contact', sa.String(), nullable=False),
    sa.Column('branch_email', sa.String(), nullable=False),
    sa.Column('branch_website', sa.String(), nullable=True),
    sa.Column('branch_fax', sa.String(), nullable=True),
    sa.Column('branch_is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('branch_id')
    )
    op.create_index(op.f('ix_branch_branch_id'), 'branch', ['branch_id'], unique=True)
    op.create_table('department',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('department_name', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_index(op.f('ix_department_department_id'), 'department', ['department_id'], unique=True)
    op.create_table('institution',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=False),
    sa.Column('institution_address', sa.String(), nullable=False),
    sa.Column('institution_phone', sa.String(), nullable=False),
    sa.Column('institution_email', sa.String(), nullable=False),
    sa.Column('institution_website', sa.String(), nullable=True),
    sa.Column('institution_fax', sa.String(), nullable=True),
    sa.Column('institution_is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('institution_id')
    )
    op.create_index(op.f('ix_institution_institution_id'), 'institution', ['institution_id'], unique=True)
    op.create_table('student',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index(op.f('ix_student_student_id'), 'student', ['student_id'], unique=True)
    op.create_table('teacher',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_index(op.f('ix_teacher_teacher_id'), 'teacher', ['teacher_id'], unique=True)
    op.create_table('usersettings',
    sa.Column('settings_id', sa.UUID(), nullable=False),
    sa.Column('notification_preference', sa.String(), nullable=False),
    sa.Column('privacy_preference', sa.String(), nullable=False),
    sa.Column('account_status', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('settings_id')
    )
    op.create_index(op.f('ix_usersettings_settings_id'), 'usersettings', ['settings_id'], unique=True)
    op.add_column('user', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(), nullable=False))
    op.add_column('user', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_user_id', table_name='user')
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=True)
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'contact_number')
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('contact_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'username')
    op.drop_column('user', 'password')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'user_id')
    op.drop_index(op.f('ix_usersettings_settings_id'), table_name='usersettings')
    op.drop_table('usersettings')
    op.drop_index(op.f('ix_teacher_teacher_id'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_index(op.f('ix_student_student_id'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_institution_institution_id'), table_name='institution')
    op.drop_table('institution')
    op.drop_index(op.f('ix_department_department_id'), table_name='department')
    op.drop_table('department')
    op.drop_index(op.f('ix_branch_branch_id'), table_name='branch')
    op.drop_table('branch')
    op.drop_index(op.f('ix_admin_admin_id'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
