"""remove total_marks field from the assignment table and add total_marks column as int

Revision ID: 7a98497b94e6
Revises: 867bc339f5a4
Create Date: 2024-11-16 13:58:57.112707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a98497b94e6'
down_revision: Union[str, None] = '867bc339f5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'total_marks')
    op.add_column('assignment', sa.Column('total_marks', sa.Integer(), nullable=False,default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'total_marks')
    op.add_column('assignment', sa.Column('total_marks', sa.String(), nullable=True))
    # ### end Alembic commands ###
