"""drop the expected_answer column and make a new expected_answer column which is array of string, question type will be nullable = true

Revision ID: 7fda5d9248b2
Revises: f348eade87c5
Create Date: 2024-11-21 19:02:38.148500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fda5d9248b2'
down_revision: Union[str, None] = 'f348eade87c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignment_question', 'question_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('assignment_question', 'expected_answer')
    op.add_column('assignment_question', sa.Column('expected_answer', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignment_question', 'expected_answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('assignment_question', sa.Column('expected_answer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('assignment_question', 'expected_answer')
    # ### end Alembic commands ###
