"""create section members table

Revision ID: 8347c059d78a
Revises: b420167411a0
Create Date: 2024-11-28 08:46:50.919706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8347c059d78a'
down_revision: Union[str, None] = 'b420167411a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectionmembers',
    sa.Column('section_member_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.section_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('section_member_id')
    )
    op.create_index(op.f('ix_sectionmembers_section_member_id'), 'sectionmembers', ['section_member_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sectionmembers_section_member_id'), table_name='sectionmembers')
    op.drop_table('sectionmembers')
    # ### end Alembic commands ###
