"""remove assignment_question_type column from the assignment table.

Revision ID: 867bc339f5a4
Revises: fd791eef0da5
Create Date: 2024-11-15 20:58:11.649540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '867bc339f5a4'
down_revision: Union[str, None] = 'fd791eef0da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'assignment_question_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('assignment_question_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
