"""created scenarios, scenario_patient and scenario_examination_finding table.

Revision ID: 8d756147c2b1
Revises: 8347c059d78a
Create Date: 2024-11-28 21:50:13.107033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d756147c2b1'
down_revision: Union[str, None] = '8347c059d78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario',
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('scenario_title', sa.String(), nullable=True),
    sa.Column('conversation', sa.JSON(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_index(op.f('ix_scenario_scenario_id'), 'scenario', ['scenario_id'], unique=True)
    op.create_table('scenario_patient',
    sa.Column('scenario_patient_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('chief_complaint', sa.String(), nullable=True),
    sa.Column('detailed_description', sa.String(), nullable=True),
    sa.Column('scenario_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.scenario_id'], ),
    sa.PrimaryKeyConstraint('scenario_patient_id')
    )
    op.create_index(op.f('ix_scenario_patient_scenario_patient_id'), 'scenario_patient', ['scenario_patient_id'], unique=True)
    op.create_table('scenario_examination_finding',
    sa.Column('scenario_examination_finding_id', sa.UUID(), nullable=False),
    sa.Column('vital_signs', sa.JSON(), nullable=True),
    sa.Column('general_appearance', sa.String(), nullable=True),
    sa.Column('cardiovascular_findings', sa.String(), nullable=True),
    sa.Column('lungs_findings', sa.String(), nullable=True),
    sa.Column('additional_findings', sa.JSON(), nullable=True),
    sa.Column('scenario_patient_id', sa.UUID(), nullable=True),
    sa.Column('scenario_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.scenario_id'], ),
    sa.ForeignKeyConstraint(['scenario_patient_id'], ['scenario_patient.scenario_patient_id'], ),
    sa.PrimaryKeyConstraint('scenario_examination_finding_id')
    )
    op.create_index(op.f('ix_scenario_examination_finding_scenario_examination_finding_id'), 'scenario_examination_finding', ['scenario_examination_finding_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_examination_finding_scenario_examination_finding_id'), table_name='scenario_examination_finding')
    op.drop_table('scenario_examination_finding')
    op.drop_index(op.f('ix_scenario_patient_scenario_patient_id'), table_name='scenario_patient')
    op.drop_table('scenario_patient')
    op.drop_index(op.f('ix_scenario_scenario_id'), table_name='scenario')
    op.drop_table('scenario')
    # ### end Alembic commands ###
