"""create student_event table and delete event table.

Revision ID: 8e45aa3abba3
Revises: 1e82bf0ba8f3
Create Date: 2024-11-26 12:28:47.992046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e45aa3abba3'
down_revision: Union[str, None] = '1e82bf0ba8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_event',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_title', sa.String(), nullable=False),
    sa.Column('event_topics', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('event_description', sa.String(), nullable=True),
    sa.Column('event_link', sa.String(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_student_event_event_id'), 'student_event', ['event_id'], unique=True)
    op.drop_index('ix_events_event_id', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_topics', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('event_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], name='events_student_id_fkey'),
    sa.PrimaryKeyConstraint('event_id', name='events_pkey')
    )
    op.create_index('ix_events_event_id', 'events', ['event_id'], unique=True)
    op.drop_index(op.f('ix_student_event_event_id'), table_name='student_event')
    op.drop_table('student_event')
    # ### end Alembic commands ###
