"""foreignkey modified

Revision ID: a37f59963b00
Revises: 71eb583fe11e
Create Date: 2024-10-09 01:18:18.520695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37f59963b00'
down_revision: Union[str, None] = '71eb583fe11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'student', 'user', ['user_id'], ['user_id'])
    op.alter_column('teacher', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'teacher', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.alter_column('teacher', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.alter_column('student', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
