"""scenario thread table created

Revision ID: a4dc3816fbb1
Revises: 8d756147c2b1
Create Date: 2024-11-30 16:06:37.979865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a4dc3816fbb1"
down_revision: Union[str, None] = "8d756147c2b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scenario_thread",
        sa.Column("scenario_thread_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("scenario_id", sa.UUID(), nullable=True),
        sa.Column("student_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenario.scenario_id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.student_id"],
        ),
        sa.PrimaryKeyConstraint("scenario_thread_id"),
    )
    op.drop_constraint(
        "scenario_examination_finding_scenario_patient_id_fkey",
        "scenario_examination_finding",
        type_="foreignkey",
    )
    op.drop_column("scenario_examination_finding", "scenario_patient_id")
    op.create_index(
        op.f("ix_scenario_thread_scenario_thread_id"),
        "scenario_thread",
        ["scenario_thread_id"],
        unique=True,
    )
    op.drop_index(
        "ix_scenario_patient_scenario_patient_id", table_name="scenario_patient"
    )
    op.drop_table("scenario_patient")
    op.add_column("scenario", sa.Column("patient_name", sa.String(), nullable=True))
    op.add_column("scenario", sa.Column("patient_age", sa.String(), nullable=True))
    op.add_column("scenario", sa.Column("patient_gender", sa.String(), nullable=True))
    op.add_column(
        "scenario", sa.Column("patient_chief_complaint", sa.String(), nullable=True)
    )
    op.add_column(
        "scenario", sa.Column("detailed_description", sa.String(), nullable=True)
    )
    op.add_column(
        "scenario", sa.Column("conversation_example", sa.JSON(), nullable=True)
    )
    op.add_column("scenario", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("scenario", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.drop_column("scenario", "conversation")
    op.alter_column(
        "scenario_examination_finding",
        "vital_signs",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "scenario_examination_finding",
        "additional_findings",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scenario_examination_finding",
        sa.Column("scenario_patient_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "scenario_examination_finding_scenario_patient_id_fkey",
        "scenario_examination_finding",
        "scenario_patient",
        ["scenario_patient_id"],
        ["scenario_patient_id"],
    )
    op.alter_column(
        "scenario_examination_finding",
        "additional_findings",
        existing_type=sa.String(),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "scenario_examination_finding",
        "vital_signs",
        existing_type=sa.String(),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.add_column(
        "scenario",
        sa.Column(
            "conversation",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("scenario", "updated_at")
    op.drop_column("scenario", "created_at")
    op.drop_column("scenario", "conversation_example")
    op.drop_column("scenario", "detailed_description")
    op.drop_column("scenario", "patient_chief_complaint")
    op.drop_column("scenario", "patient_gender")
    op.drop_column("scenario", "patient_age")
    op.drop_column("scenario", "patient_name")
    op.create_table(
        "scenario_patient",
        sa.Column(
            "scenario_patient_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("age", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("gender", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("chief_complaint", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "detailed_description", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("scenario_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenario.scenario_id"],
            name="scenario_patient_scenario_id_fkey",
        ),
        sa.PrimaryKeyConstraint("scenario_patient_id", name="scenario_patient_pkey"),
    )
    op.create_index(
        "ix_scenario_patient_scenario_patient_id",
        "scenario_patient",
        ["scenario_patient_id"],
        unique=True,
    )
    op.drop_index(
        op.f("ix_scenario_thread_scenario_thread_id"), table_name="scenario_thread"
    )
    op.drop_table("scenario_thread")
    # ### end Alembic commands ###
