"""created TemplateCourseAccess table

Revision ID: a6326c69d7df
Revises: 4f636593f906
Create Date: 2024-10-27 13:36:57.219314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6326c69d7df'
down_revision: Union[str, None] = '4f636593f906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_course_access',
    sa.Column('template_course_access_id', sa.UUID(), nullable=False),
    sa.Column('template_course_id', sa.UUID(), nullable=True),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ),
    sa.ForeignKeyConstraint(['template_course_id'], ['template_course.template_course_id'], ),
    sa.PrimaryKeyConstraint('template_course_access_id')
    )
    op.create_index(op.f('ix_template_course_access_template_course_access_id'), 'template_course_access', ['template_course_access_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_course_access_template_course_access_id'), table_name='template_course_access')
    op.drop_table('template_course_access')
    # ### end Alembic commands ###
