"""rename the matric_id field

Revision ID: a80b57e4ebf0
Revises: 6404218d6e04
Create Date: 2024-12-11 12:05:02.708144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80b57e4ebf0'
down_revision: Union[str, None] = '6404218d6e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'metric_id', new_column_name='matric_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'matric_id', new_column_name='metric_id')
    # ### end Alembic commands ###
