"""created created assignment submission table and assignment submission answer table.

Revision ID: b420167411a0
Revises: 8e45aa3abba3
Create Date: 2024-11-27 23:13:16.340892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b420167411a0'
down_revision: Union[str, None] = '8e45aa3abba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('announcement_title', sa.String(), nullable=False),
    sa.Column('announcement_description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.section_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ),
    sa.PrimaryKeyConstraint('announcement_id')
    )
    op.create_index(op.f('ix_announcement_announcement_id'), 'announcement', ['announcement_id'], unique=True)
    op.create_table('assignment_submission_answer',
    sa.Column('assignment_submission_answer_id', sa.UUID(), nullable=False),
    sa.Column('answers', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('total_marks_after_eval', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('assignment_submission_id', sa.UUID(), nullable=True),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_submission_id'], ['assignment_submission.assignment_submission_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['assignment_question.assignment_question_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('assignment_submission_answer_id')
    )
    op.create_index(op.f('ix_assignment_submission_answer_assignment_submission_answer_id'), 'assignment_submission_answer', ['assignment_submission_answer_id'], unique=True)
    op.add_column('assignment_submission', sa.Column('total_marks_after_eval', sa.Integer(), nullable=True))
    op.add_column('assignment_submission', sa.Column('evaluated', sa.Boolean(), nullable=True))
    op.add_column('assignment_submission', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('assignment_submission', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('assignment_submission', 'grade')
    op.drop_column('assignment_submission', 'submitted_at')
    op.drop_column('assignment_submission', 'grading')
    op.drop_column('assignment_submission', 'submitted_file')
    op.drop_column('assignment_submission', 'modified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submission', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('assignment_submission', sa.Column('submitted_file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('assignment_submission', sa.Column('grading', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('assignment_submission', sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('assignment_submission', sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('assignment_submission', 'updated_at')
    op.drop_column('assignment_submission', 'created_at')
    op.drop_column('assignment_submission', 'evaluated')
    op.drop_column('assignment_submission', 'total_marks_after_eval')
    op.drop_index(op.f('ix_assignment_submission_answer_assignment_submission_answer_id'), table_name='assignment_submission_answer')
    op.drop_table('assignment_submission_answer')
    op.drop_index(op.f('ix_announcement_announcement_id'), table_name='announcement')
    op.drop_table('announcement')
    # ### end Alembic commands ###
