"""ThreadMsg Table Created

Revision ID: b65da65418ad
Revises: a4dc3816fbb1
Create Date: 2024-11-30 17:57:45.715488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b65da65418ad'
down_revision: Union[str, None] = 'a4dc3816fbb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_thread_message',
    sa.Column('scenario_thread_message_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('scenario_thread_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_thread_id'], ['scenario_thread.scenario_thread_id'], ),
    sa.PrimaryKeyConstraint('scenario_thread_message_id')
    )
    op.create_index(op.f('ix_scenario_thread_message_scenario_thread_message_id'), 'scenario_thread_message', ['scenario_thread_message_id'], unique=True)
    op.drop_column('scenario_thread', 'type')
    op.drop_column('scenario_thread', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_thread', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scenario_thread', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_scenario_thread_message_scenario_thread_message_id'), table_name='scenario_thread_message')
    op.drop_table('scenario_thread_message')
    # ### end Alembic commands ###
