"""thread_name added

Revision ID: b663f7ca85ca
Revises: 7a934fbc0afe
Create Date: 2024-12-06 21:11:03.789390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b663f7ca85ca'
down_revision: Union[str, None] = '7a934fbc0afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_thread', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario_thread', 'name')
    # ### end Alembic commands ###
