"""add created_at and updated at, fields to the section and course content tables.

Revision ID: c20995335808
Revises: 7816a594ecd9
Create Date: 2024-12-02 13:12:34.033930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20995335808'
down_revision: Union[str, None] = '7816a594ecd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_materials', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('course_materials', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('section_exclusive_content', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('section_exclusive_content', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section_exclusive_content', 'updated_at')
    op.drop_column('section_exclusive_content', 'created_at')
    op.drop_column('course_materials', 'updated_at')
    op.drop_column('course_materials', 'created_at')
    # ### end Alembic commands ###
