"""one-to-one relationship user,student,teacher,admin

Revision ID: c48f8267c5f9
Revises: a6326c69d7df
Create Date: 2024-10-30 08:10:31.265921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48f8267c5f9'
down_revision: Union[str, None] = 'a6326c69d7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
