"""super_user field added

Revision ID: c62ace70954c
Revises: 666ab5e80346
Create Date: 2024-10-09 00:52:28.106284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62ace70954c'
down_revision: Union[str, None] = '666ab5e80346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.drop_index('ix_usersettings_settings_id', table_name='user_settings')
    op.create_index(op.f('ix_user_settings_settings_id'), 'user_settings', ['settings_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_settings_id'), table_name='user_settings')
    op.create_index('ix_usersettings_settings_id', 'user_settings', ['settings_id'], unique=True)
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###
