"""add branch_id to template_course table

Revision ID: f348eade87c5
Revises: 7a98497b94e6
Create Date: 2024-11-20 18:59:54.747197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f348eade87c5'
down_revision: Union[str, None] = '7a98497b94e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_course', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'template_course', 'branch', ['branch_id'], ['branch_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'template_course', type_='foreignkey')
    op.drop_column('template_course', 'branch_id')
    # ### end Alembic commands ###
