"""In the assignment_material table add title, description and library_term_id column and remove the material column. In the assignment table, remove the assignment_question_type column.Create events and notes table

Revision ID: fd791eef0da5
Revises: 36a78aca72b6
Create Date: 2024-11-15 20:03:04.155712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd791eef0da5'
down_revision: Union[str, None] = '36a78aca72b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_title', sa.String(), nullable=False),
    sa.Column('event_topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('event_description', sa.String(), nullable=True),
    sa.Column('event_link', sa.String(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=True)
    op.create_table('notes',
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('note_title', sa.String(), nullable=False),
    sa.Column('note_content', sa.String(), nullable=True),
    sa.Column('note_markdown_content', sa.String(), nullable=True),
    sa.Column('note_teacher', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index(op.f('ix_notes_note_id'), 'notes', ['note_id'], unique=True)
    op.add_column('assignment_material', sa.Column('title', sa.String(), nullable=True))
    op.add_column('assignment_material', sa.Column('description', sa.String(), nullable=True))
    op.add_column('assignment_material', sa.Column('library_item_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'assignment_material', 'global_library', ['library_item_id'], ['library_id'])
    op.drop_column('assignment_material', 'matrial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_material', sa.Column('matrial', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assignment_material', type_='foreignkey')
    op.drop_column('assignment_material', 'library_item_id')
    op.drop_column('assignment_material', 'description')
    op.drop_column('assignment_material', 'title')
    op.drop_index(op.f('ix_notes_note_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
