name: CI/CD Pipeline for FastAPI Deployment

on:
  push:
    branches:
      - main  # Trigger the deployment when code is pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout the code
        uses: actions/checkout@v2

      # Step 2: Set up the SSH agent to authenticate with the server
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Debugging Step: Test SSH connection with verbose output
      - name: Test SSH connection
        run: ssh -vvv -o StrictHostKeyChecking=no root@203.161.38.194 echo "Connection successful"

      # Step 3: Copy the application code to the correct directory on the server using rsync
      - name: Copy files to the server
        run: |
          ssh -o StrictHostKeyChecking=no root@203.161.38.194 'mkdir -p /home/fastapi/lms-backend'
          rsync -avz --exclude '.git' --exclude 'node_modules' ./ root@203.161.38.194:/home/fastapi/lms-backend/

      # Step 4: SSH into the server and deploy the updated application
      - name: Deploy the application
        run: |
          ssh -o StrictHostKeyChecking=no root@203.161.38.194 << 'EOF'
            cd /home/fastapi/lms-backend
            # sudo docker-compose -f docker-compose.yml down
            sudo docker-compose -f docker-compose-dev.yml up --build -d
            sudo docker image prune -f
            # General error log check (you can customize or expand these patterns)
            ERROR_LOG=$(sudo docker-compose logs web | grep -E -i 'error|exception|traceback|undefinedtable|fail|fatal')
            if [[ -n "$ERROR_LOG" ]]; then
              echo "Critical error found in web_1 logs:"
              echo "$ERROR_LOG"
              exit 1  # Fail the deployment if any error is found
            fi
          EOF
